//DETAILS PAGE ACTIONS
export const FILTER_DETAILS = 'FILTER_DETAILS';

//GRID ACTIONS
export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE';
export const FILTER = 'FILTER';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const ADD_DATA= 'ADD_DATA';
